# @package _global_
# changes batch size and num_classes if resnet is used with cifar100
# more info: https://hydra.cc/docs/patterns/specializing_config
model:
  batch_size: 128
  network:
    num_classes: 100