# @package _global_
# changes default model parameter if resnet is used with cifar100
# more info: https://hydra.cc/docs/patterns/specializing_config
model:
  batch_size: 64
  network:
    num_classes: 10

