# @package _global_
# changes batch size and num_classes if resnet is used with cifar10
# more info: https://hydra.cc/docs/patterns/specializing_config
model:
  batch_size: 64
  network:
    num_classes: 10
