# @package _global_
checkpoint: null # add checkpoint path here
tensorboard: true
auto_cpu_if_no_gpu: true
device: cuda:0
save: true

dataset:
  train:
    use: true
  val:
    use: true
  test:
    use: true
