defaults:
  - dataset: mnist
  - model: lenet
  - dataset_model: ${defaults.0.dataset}_${defaults.1.model} # change when Hydra 1.1 releases
    optional: true # more info: https://hydra.cc/docs/patterns/specializing_config
  - loss: ce


