# @package _group_
_target_: phuber.network.resnet18
# num_classes gets set to 10 when used with cifar-10, to 100 when used with cifar-100
# more info: https://hydra.cc/docs/patterns/specializing_config
