# @package _group_
epochs: 100
batch_size: 64

network:
  _target_: torchvision.models.resnet50
  pretrained: false
  num_classes: 10 # gets overridden to 100 when used with cifar-100

optimizer:
  _target_: torch.optim.SGD
  lr: 0.001
  weight_decay: 5e-3
  momentum: 0.1