# @package _global_
# Default hyper-parameters for lenet used with MNIST
# more info: https://hydra.cc/docs/patterns/specializing_config
hparams:
  epochs: 20
  batch_size: 32

  optimizer:
    _target_: torch.optim.Adam
    lr: 0.001
    weight_decay: 1e-3

  scheduler:
    _target_: phuber.scheduler.ExponentialDecayLR
    decay_rate: 0.1
    decay_steps: 10000
    staircase: False